"""change payment table

Revision ID: 89432dcc83b1
Revises: 12309f90eaef
Create Date: 2025-04-09 10:28:10.891256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89432dcc83b1'
down_revision: Union[str, None] = '12309f90eaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'store_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('store_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
