"""change deleting

Revision ID: 9cb4cce55045
Revises: 5db6e883e437
Create Date: 2024-12-12 22:46:56.410475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb4cce55045'
down_revision: Union[str, None] = '5db6e883e437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_telegram_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['telegram_id'], ['telegram_id'], ondelete='SET NULL')
    op.alter_column('subscriptions', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('subscriptions_payment_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_payment_id_fkey', 'subscriptions', 'payments', ['payment_id'], ['id'])
    op.alter_column('subscriptions', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_telegram_id_fkey', 'payments', 'users', ['telegram_id'], ['telegram_id'])
    # ### end Alembic commands ###
