"""change sub table

Revision ID: b89a4e229094
Revises: f2c43e69cc5d
Create Date: 2024-12-13 02:37:20.870813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89a4e229094'
down_revision: Union[str, None] = 'f2c43e69cc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_payment_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subscriptions_payment_id_fkey', 'subscriptions', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
