"""change payments

Revision ID: f2b1d551cd95
Revises: 793009d417b8
Create Date: 2024-12-06 16:31:56.601027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b1d551cd95'
down_revision: Union[str, None] = '793009d417b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_subscription_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('payments_subscription_id_fkey', 'payments', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
