"""add fk

Revision ID: f636d7cc3180
Revises: d73b54943847
Create Date: 2024-12-06 17:10:37.025634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f636d7cc3180'
down_revision: Union[str, None] = 'd73b54943847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_receipt_id', 'payments', type_='unique')
    op.add_column('subscriptions', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subscriptions', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'payment_id')
    op.create_unique_constraint('unique_receipt_id', 'payments', ['receipt_id'])
    # ### end Alembic commands ###
