"""change column sub

Revision ID: fad7f5a68191
Revises: 9cb4cce55045
Create Date: 2024-12-12 23:42:42.254835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad7f5a68191'
down_revision: Union[str, None] = '9cb4cce55045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.drop_column('subscriptions', 'subscription_isActive')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('subscription_isActive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'isActive')
    # ### end Alembic commands ###
