name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: LP Bot
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Проверяем существование директории
            if [ -d "~/payment-alpha-bot" ]; then
              echo "Директория существует, выполняем обновление"
              cd ~/payment-alpha-bot
              git status
              git checkout main
              git pull
              docker compose up -d --build
            else
              echo "Директория не существует, выполняем клонирование"
              cd ~
              git clone git@github.com:Jlumon4ek/payment-alpha-bot.git
              cd ~/payment-alpha-bot
              docker compose up -d --build
            fi

            # Проверяем результат
            echo "Текущий коммит в репозитории:"
            cd ~/payment-alpha-bot
            git log -1 --format="%H %s"

            echo "Список запущенных контейнеров:"
            docker ps
